### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'major'

### ISSUE THREAD

**Issue by sunnvor** [OpenGene/AfterQC#10]
Hi,
Firstly, I am new to Linux, so the solution might be obvious, but I can't get AfterQC to run. I keep getting this error:

Traceback (most recent call last):
  File "after.py", line 208, in <module>
    main()
  File "after.py", line 175, in main
    if sys.version_info.major >2:
AttributeError: 'tuple' object has no attribute 'major'

I tried the -h option and adding a path to my data but get the same error. I installed the editdistance with the make command in the AfterQC directory. I am using python version 2.6.6.

**Comment by sfchen** [comment]
Hi, can you run python, and paste the output of following commands:

``` python
import sys
print sys.version_info
```

**Comment by sunnvor** [comment]
Python 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
import sys

> > > import sys
> > > print sys.version_info
> > > (2, 6, 6, 'final', 0)

**Comment by sfchen** [comment]
Okay, thanks.

Seems your python is different from normal distribution.

I will commit an update to fix this issue on your system soon. I will update this issue once it is done.

**Comment by sunnvor** [comment]
Thank you.

**Comment by sfchen** [comment]
Updated. Please check out the latest version using `git pull -r`

**Comment by sunnvor** [comment]
Thank you it seems to be working now.

**Comment by sfchen** [comment]
Good, closing this issue!
