### ISSUE TITLE
Deafult multiprocessing behavior

### ISSUE THREAD

**Issue by alnf** [OpenGene/AfterQC#15]
Do you create as many jobs with python multiprocessing as there are input files? I ran it with default parameters and it seemed to occupy all 32 cores. Is it possible to limit the number of jobs created, cause it is not always possible to use all the resources when computing on shared server.

**Comment by alnf** [comment]
Oh no, I'm blind. Closing because of duplicate issue:)

**Comment by sfchen** [comment]
Thanks @alnf 

I will implement this feature and make a new release in this week.
