### ISSUE TITLE
Packaging: make available on Pypi/conda

### ISSUE THREAD

**Issue by matthdsm** [OpenGene/AfterQC#23]
Hi,

Would it be possible to make this package available in Pypi and/or conda? This would greatly improve the accessibility of your tool.
We're interested in integrating AfterQC in our QC pipeline, but this depends on the package being available from Pypi or Conda.

Thanks!
M

**Comment by sfchen** [comment]
Thanks for this good suggestion.

How about add it to BioConda first? PyPy is suggested for AfterQC due to performance consideration, but is not compatible with pypi/conda distribution.

**Comment by matthdsm** [comment]
No problem, I'd have packaged it for bioconda myself if your suggestion would have been Pypi.

Thanks!
M

**Comment by matthdsm** [comment]
Conda recipe:
bioconda/bioconda-recipes#6037

**Comment by sfchen** [comment]
@matthdsm thanks:)

**Comment by coolmak32** [comment]
Hi, I installed Bioconda and gave the command conda install afterqc. It generates the error that there is no such package. What should I do to fix it?

**Comment by colindaven** [comment]
Good idea on bioconda.

afterqc is present as v. 0.9.6. Check you have your channels sorted correctly @coolmak32

**Comment by coolmak32** [comment]
Hi Colin,
Hope you are doing great man. I wanted to ask you that how to select right
file for the generation of an index using STAR. I am trying to get genome
as well gene annotation data from ensembl but there are numerous files in
every directory. Also as I have told you earlier that my samples had
polyribomes associated with mRNA transcripts mostly, so should I create
index using cDNA data file or whole Genome data file.


Thanks,


Kuldeep Makwana
(Ph.D. candidate regulatory biology)
SR 271,BGES
Cleveland State University.
216-262-9156
