### ISSUE TITLE
filter only for poly-X but nothing else

### ISSUE THREAD

**Issue by avilella** [OpenGene/AfterQC#31]
What would be the command-line to run AfterQC in order to filter only for poly-X reads but nothing else?

**Comment by sfchen** [comment]
Do you want to filter only polyG, or filter all of polyA/T/C/G?

**Comment by avilella** [comment]
all of polyA/T/C/G

**Comment by avilella** [comment]
Just to clarify, what I intend to do is to filter out the read pairs that look like polyA/T/C/G, but not trim or get rid of the reads that don't look like polyA/T/C/G but have low Q-scores or other issues.

**Comment by sfchen** [comment]
use following option to disable other trimmer / filters
```
-f0 -t0 -q0 -n1000 -s1000
```

**Comment by avilella** [comment]
Brilliant, thanks!

**Comment by avilella** [comment]
I tried it with the command-line below, but it results in this:

> 
> # /home/avilella/AfterQC/after.py --no_overlap -f0 -t0 -q0 -n1000 -s1000 --read1_file=/home/avilella/CEGX_Run499/CEGX_Run499_enigma-12345678/CEG67_125_3-77840783/CEG67-125-3_S3_L001_R1_001.fastq.gz  --read2_file=/home/avilella/CEGX_Run499/CEGX_Run499_enigma-12345678/CEG67_125_3-77840783/CEG67-125-3_S3_L001_R2_001.fastq.gz --good_output_folder=/home/avilella/CEGX_Run499/CEGX_Run499_enigma-12345678/CEG67_125_3-77840783//afqc
> Traceback (most recent call last):
>   File "/home/avilella/AfterQC/after.py", line 228, in <module>
>     main()
>   File "/home/avilella/AfterQC/after.py", line 222, in main
>     processOptions(options)
>   File "/home/avilella/AfterQC/after.py", line 175, in processOptions
>     filter.run()
>   File "/home/avilella/AfterQC/preprocesser.py", line 773, in run
>     self.addFiguresToReport(reporter)
>   File "/home/avilella/AfterQC/preprocesser.py", line 788, in addFiguresToReport
>     reporter.addFigure('Read1 per base discontinuity after filtering', self.r1qc_postfilter.discontinuityPlotly("r1_post_discontinuity", 'Read1 discontinuity curve after filtering'), 'r1_post_discontinuity', "")
>   File "/home/avilella/AfterQC/qualitycontrol.py", line 234, in discontinuityPlotly
>     json_str += "var layout={title:'" + title + "', xaxis:{title:'cycles'}, yaxis:{title:'discontinuity', range:" + makeRange(0.0, max(self.meanDiscontinuity)*1.5) + "}};\n"
> ValueError: max() arg is an empty sequence
>

**Comment by avilella** [comment]
I tried it with the command below, but it results in this:
```

# /home/avilella/AfterQC/after.py --no_overlap -f0 -t0 -q0 -n1000 -s1000 --read1_file=/home/avilella/CEGX_Run499/CEGX_Run499_enigma-12345678/CEG67_125_3-77840783/CEG67-125-3_S3_L001_R1_001.fastq.gz  --read2_file=/home/avilella/CEGX_Run499/CEGX_Run499_enigma-12345678/CEG67_125_3-77840783/CEG67-125-3_S3_L001_R2_001.fastq.gz --good_output_folder=/home/avilella/CEGX_Run499/CEGX_Run499_enigma-12345678/CEG67_125_3-77840783//afqc
Traceback (most recent call last):
  File "/home/avilella/AfterQC/after.py", line 228, in <module>
    main()
  File "/home/avilella/AfterQC/after.py", line 222, in main
    processOptions(options)
  File "/home/avilella/AfterQC/after.py", line 175, in processOptions
    filter.run()
  File "/home/avilella/AfterQC/preprocesser.py", line 773, in run
    self.addFiguresToReport(reporter)
  File "/home/avilella/AfterQC/preprocesser.py", line 788, in addFiguresToReport
    reporter.addFigure('Read1 per base discontinuity after filtering', self.r1qc_postfilter.discontinuityPlotly("r1_post_discontinuity", 'Read1 discontinuity curve after filtering'), 'r1_post_discontinuity', "")
  File "/home/avilella/AfterQC/qualitycontrol.py", line 234, in discontinuityPlotly
    json_str += "var layout={title:'" + title + "', xaxis:{title:'cycles'}, yaxis:{title:'discontinuity', range:" + makeRange(0.0, max(self.meanDiscontinuity)*1.5) + "}};\n"
ValueError: max() arg is an empty sequence

```

**Comment by avilella** [comment]
This is with 2x150bp pairs of fastq.gz files.

**Comment by sfchen** [comment]
Sorry, I made a mistake, it should be:
```
-f0 -t0 -q0 -n1000 -s0
```

**Comment by avilella** [comment]
I tested it and it works now. Thanks again for the prompt reply!
