### ISSUE TITLE
File exists: './QC'

### ISSUE THREAD

**Issue by stephenturner** [OpenGene/AfterQC#5]
Even when removing previous runs' QC folders, I still get an error when running after.py

```
  File "/home/sdt5z/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: './QC'
```

**Comment by sfchen** [comment]
Can you paste the full call stack of the error dump?

I need to know which code line the error is raised

**Comment by sfchen** [comment]
How many fastq files in your data folder? If you run it again, will it work?

**Comment by sfchen** [comment]
Hi @stephenturner 

can you please `git pull -r` to checkout the latest code, and try again? Thanks!

**Comment by stephenturner** [comment]
thanks, got rid of that error.

**Comment by sfchen** [comment]
Closing...
